---
title: "Replication of Study "Who's Responsible for the Digital Divide? Public Perceptions and Policy Implications" by Epstein et al. (2011, The Information Society)"
author: "Shirley Agustin (shagustin@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

In this experiment, we learn that through framing, individuals will place the responsibility for the digital divide onto different institutions. The digital divide is an issue that I have been interested in exploring further, as tackling disparities faced by vulnerable populations is a top priority as I shape my professional goals. This experiment, in particular, aligns with my goals of using communication theories and data science to learn how to effectively advocate for the necessary resources underserved communities need. It helps me understand how individuals perceive which institutions they hold accountable for addressing their needs.

The experiment was conducted through a national omnibus poll. This experiment consisted of 500 interviews via telephone interviewing software. This software randomly assigned the participants to two different framing conditions regarding the definition of the digital divide. Participants would then move on to answering who holds responsibility for the digital divide, presented through standardized response options.

Challenges that came up include the lack of participants in this experiment. The experiment was part of a national omnibus poll, which may have led to a greater response rate, but since this experiment focused only on a single topic, we may not be able to garner a larger participation rate. Furthermore, the experiment was conducted through telephone interviewing software, which may not be provided by the university or may not be available at no cost. This could lead us to deliver the poll in a different format, which may affect the results of the experiment.

[GitHub Repository](https://github.com/shirleyagustin/epstein2011)
[Original Paper](https://github.com/shirleyagustin/epstein2011/blob/main/original_paper/PublicPerception_Original.pdf)

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
